name = "«json-schema»"
version = "0.1.0"
defaultTargets = ["bowtie"]
testDriver = "testJsonSchema"

[[lean_lib]]
name = "JsonSchema"

[[lean_lib]]
name = "Harness"

[[lean_lib]]
name = "JsonSchemaTesting"

[[require]]
name = "lean-uri"
git = "https://github.com/josephmckinsey/lean-uri"
rev = "v4.23.0"

[[require]]
name = "Regex"
git = "https://github.com/bergmannjg/regex"
rev = "v4.25.0"

[[lean_exe]]
name = "bowtie"
root = "Main"

[[lean_exe]]
name = "testJsonSchema"
root = "TestRunner"
