name = "«json-schema»"
defaultTargets = ["bowtie"]

[[lean_lib]]
name = "JsonSchema"

[[lean_lib]]
name = "Harness"

[[require]]
name = "lean-uri"
path = "../lean-uri"

[[lean_exe]]
name = "bowtie"
root = "Main"
